export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const CREATE_PORTFOLIO = "CREATE_PORTFOLIO";
export const GET_PORTFOLIOS = "GET_PORTFOLIOS";
export const GET_PORTFOLIO_BY_NAME = "GET_PORTFOLIO_BY_NAME";
export const ADD_TO_PORTFOLIO = "ADD_TO_PORTFOLIO";
export const DELETE_FROM_PORTFOLIO = "DELETE_FROM_PORTFOLIO";
export const DELETE_PORTFOLIO = "DELETE_PORTFOLIO";

export const ADD_WATCHLIST = "ADD_WATCHLIST";
export const GET_WATCHLIST = "GET_WATCHLIST";
export const DELETE_WATCHLIST = "DELETE_WATCHLIST";

export const GET_TOPSTOCKS = "GET_TOPSTOCKS";

export const GET_NEWS = "GET_NEWS";

export const IS_LOADING = "IS_LOADING";